src/CoolCat/Areas/Admin/Controllers/PluginsController.cs
using CoolCat.Core.Contracts;
using CoolCat.Core.DomainModel;
using CoolCat.Core.Mvc.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace CoolCat.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class PluginsController : Controller
    {
        private readonly IPluginManager _pluginManager = null;
        private readonly IReferenceContainer _referenceContainer = null;
        private readonly IDbConnectionFactory _dbConnectionFactory = null;
        private readonly IQueryDocumentation _queryDocumentation = null;

        public PluginsController(IPluginManager pluginManager, IReferenceContainer referenceContainer, IDbConnectionFactory dbConnectionFactory, IQueryDocumentation queryDocumentation)
        {
            _pluginManager = pluginManager;
            _referenceContainer = referenceContainer;
            _dbConnectionFactory = dbConnectionFactory;
            _queryDocumentation = queryDocumentation;
        }


        public IActionResult Document()
        {
            var documents = _queryDocumentation.GetAllDocuments();
            return View(documents);
        }

        public IActionResult Assemblies()
        {
            System.Collections.Generic.List<CachedReferenceItemKey> items = _referenceContainer.GetAll();

            return View(items);
        }

        public IActionResult Index()
        {
            return View(_pluginManager.GetAllPlugins());
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Upload()
        {
            PluginPackage package = new PluginPackage(Request.GetPluginStream(), _dbConnectionFactory);
            _pluginManager.AddPlugins(package);
            return RedirectToAction("Index");
        }

        public IActionResult Enable(Guid id)
        {
            _pluginManager.EnablePlugin(id);
            return RedirectToAction("Index");
        }

        public IActionResult Disable(Guid id)
        {
            _pluginManager.DisablePlugin(id);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(Guid id)
        {
            _pluginManager.DeletePlugin(id);

            return RedirectToAction("Index");
        }
    }
}

src/CoolCat/Areas/Admin/Controllers/SystemController.cs
using CoolCat.Core.Consts;
using CoolCat.Core.Contracts;
using CoolCat.Core.DTOs;
using CoolCat.Models;
using CoolCat.Utilities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Claims;

namespace CoolCat.Controllers
{
    [Area("Admin")]
    public class SystemController : Controller
    {
        private readonly ISystemManager _systemManager;
        private readonly IPluginManager _pluginManager;
        private readonly IDbConnectionFactory _dbConnectionFactory;


        public SystemController(ISystemManager systemManager, IPluginManager pluginManager, IDbConnectionFactory dbConnectionFactory)
        {
            _systemManager = systemManager;
            _pluginManager = pluginManager;
            _dbConnectionFactory = dbConnectionFactory;
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (User != null)
            {
                return RedirectToAction("Dashboard", "Home", new { Area = "Admin" });
            }

            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginDTO dto)
        {
            if (ModelState.IsValid)
            {
                //Fake login
                if (dto.UserName == "admin" && dto.Password == "admin")
                {
                    var authProperties = new AuthenticationProperties
                    {

                        RedirectUri = "/Admin/Home/Dashboard"
                    };


                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, dto.UserName)
                    };

                    var claimsIdentity = new ClaimsIdentity(
    claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    HttpContext.SignInAsync(
   CookieAuthenticationDefaults.AuthenticationScheme,
   new ClaimsPrincipal(claimsIdentity),
   authProperties);
                }
                else
                {
                    ModelState.AddModelError("", "User name or password is wrong.");
                }
            }

            return View();
        }

        public IActionResult Setup()
        {
            PresetPluginLoader presetPluginLoader = new PresetPluginLoader();
            List<string> plugins = presetPluginLoader.LoadPlugins();

            if (plugins.Count == 0)
            {
                _systemManager.MarkAsInstalled();
                return RedirectToAction("Index", "Home");
            }

            return View(plugins);
        }

        [HttpPost]
        public IActionResult Install([FromBody] SetupModulesModel model)
        {
            if (model != null && model.Modules != null)
            {
                foreach (string module in model.Modules)
                {
                    using (FileStream fs = new FileStream(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, GlobalConst.PresetFolder, module), FileMode.Open))
                    {
                        _pluginManager.AddPlugins(new Core.DomainModel.PluginPackage(fs, _dbConnectionFactory));
                    }
                }
            }

            _systemManager.MarkAsInstalled();

            return Ok();
        }

        [HttpGet("SiteSettings")]
        [Authorize]
        public IActionResult SiteSettings()
        {
            var settings = _systemManager.GetSiteSettings();
            return View(settings);
        }

        [HttpPost("SiteSettings")]
        [Authorize]
        public IActionResult SiteSettings(SiteSettingsDTO dto)
        {
            _systemManager.SaveSiteSettings(dto);

            var settings = _systemManager.GetSiteSettings();
            return View(settings);
        }


    }
}

src/CoolCat/Controllers/CommonController.cs
using CoolCat.Core;
using CoolCat.Core.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace CoolCat.Controllers
{
    public class CommonController : Controller
    {
        private readonly ISystemManager _systemManager;
        private readonly IPluginManager _pluginManager;


        public CommonController(ISystemManager systemManager, IPluginManager pluginManager)
        {
            _systemManager = systemManager;
            _pluginManager = pluginManager;
        }

        [HttpGet("~/Common/GetSiteCSS")]
        public IActionResult GetSiteCSS()
        {
            var settings = _systemManager.GetSiteSettings();

            if (!string.IsNullOrEmpty(settings.SiteCSS))
            {
                return Content(settings.SiteCSS, "text/css");
            }

            return null;
        }


        [HttpGet("~/Common/GetModuleCSS")]
        public IActionResult GetModuleCSS(string moduleName, string fileName)
        {
            var fileContent = PluginsLoadContexts.Get(moduleName).LoadResource(fileName);

            return new FileContentResult(fileContent, "text/css");
        }

        [HttpGet("~/CommonS/GetModuleScript")]
        public IActionResult GetModuleScript(string moduleName, string fileName)
        {
            var fileContent = PluginsLoadContexts.Get(moduleName).LoadResource(fileName);
            return new FileContentResult(fileContent, "text/javascript");
        }
    }
}

src/CoolCat/Views/Shared/_AdminLayout.cshtml
@inject CoolCat.Core.Contracts.ISystemManager SystemManager
@using CoolCat.Core.Mvc.Extensions;
@{
    var contexts = CoolCat.Core.PluginsLoadContexts.All();
    var menus = contexts.SelectMany(p => p.GetPages()).ToList();

}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoolCat</title>


    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="@Url.Action("GetSiteCSS", "Common")" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    @RenderSection("Header", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="Admin" asp-controller="Home" asp-action="Dashboard">
                    <img src="~/logo_small.png" width="45px" />
                    <span style="color: #5cbedf;">CoolCat</span>
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Dashboard">Home</a>
                        </li>
                        @if (SystemManager.CheckInstall())
                        {
                            <li class="dropdown">
                                <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">System<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Plugins" asp-action="Assemblies">Assemblies</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Plugins" asp-action="Index">Plugins</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Plugins" asp-action="Document">Documentation</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="System" asp-action="SiteSettings">Site Settings</a>
                                    </li>

                                </ul>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Back</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="footLeft">&copy; 2020 - CoolCat Framework v1.0.1</div>
            <div class="footRight"><img src="~/logo2.png" /></div>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/lib/bootstrap/dist/js/bootstrap-datepicker.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/CoolCat/Views/Shared/_Layout.cshtml
@inject CoolCat.Core.Contracts.ISystemManager SystemManager
@using CoolCat.Core.Mvc.Extensions;
@{
    var contexts = CoolCat.Core.PluginsLoadContexts.All();
    var menus = contexts.SelectMany(p => p.GetPages()).ToList();

}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoolCat</title>


    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="@Url.Action("GetSiteCSS", "System")" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    @RenderSection("Header", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/logo_small.png" width="45px" />
                    <span style="color: #5cbedf;">CoolCat</span>
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SystemManager.CheckInstall())
                        {
                            foreach (var item in menus)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" href="/Modules/@item.Url">@item.PageName</a>
                                </li>
                            }

                            <li class="nav-item">
                                <a class="nav-link text-dark" href="/Admin/System/Login">Admin Portal</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="footLeft">&copy; 2020 - CoolCat Framework v1.0.1</div>
            <div class="footRight"><img src="~/logo2.png" /></div>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/lib/bootstrap/dist/js/bootstrap-datepicker.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>