src/DemoModules/BookLibrary/ViewModels/BookDetailsViewModel.cs
using System;

namespace BookLibrary.ViewModels
{
    public class BookDetailsViewModel
    {
        public Guid BookId { get; set; }

        public string BookName { get; set; }

        public string ISBN { get; set; }

        public DateTime DateIssued { get; set; }
    }
}

src/DemoModules/BookLibrary/ViewModels/BookListViewModel.cs
using System;

namespace BookLibrary.ViewModels
{
    public class BookListViewModel
    {
        public Guid BookId { get; set; }

        public string BookName { get; set; }

        public string ISBN { get; set; }

        public DateTime DateIssued { get; set; }
    }
}

src/DemoModules/BookLibrary/Controllers/BookController.cs
using BookLibrary.DAL;
using BookLibrary.ViewModels;
using CoolCat.Core.Attributes;
using CoolCat.Core.Contracts;
using CoolCat.Core.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace BookLibrary.Controllers
{
    [Area(ModuleDefiniation.MODULE_NAME)]
    public class BookController : CoolCatController
    {
        private readonly BookDAL _bookDAL;
        private readonly INotificationRegister _notificationRegister;

        public BookController(IDataStore dataStore, IDbConnectionFactory dbConnectionFactory, INotificationRegister notificationRegister) : base(ModuleDefiniation.MODULE_NAME, dataStore)
        {
            _bookDAL = new BookDAL(dbConnectionFactory);
            _notificationRegister = notificationRegister;
        }

        [HttpGet]
        [Page("Book Library")]
        public IActionResult AvailableBooks()
        {
            var books = JsonConvert.DeserializeObject<List<BookListViewModel>>(Query("BookInventory", "Available_Books", string.Empty));

            return View(books);
        }

        [HttpPut]
        public IActionResult RentBook(Guid bookId)
        {
            var book = JsonConvert.DeserializeObject<BookDetailsViewModel>(Query("BookInventory", "Book_Details", JsonConvert.SerializeObject(new { bookId })));

            var date = DateTime.Today;

            _bookDAL.RentBook(new Dtos.RentBookDTO
            {
                BookId = bookId,
                BookName = book.BookName,
                DateIssued = book.DateIssued,
                ISBN = book.ISBN,
                RentDate = date
            });

            _notificationRegister.Publish("BookOutEvent", JsonConvert.SerializeObject(new
            {
                BookId = bookId,
                OutDate = date
            }));

            return Json(new
            {
                result = true
            });
        }

        [HttpPut]
        public IActionResult ReturnBook(Guid rentId)
        {
            var bookId = _bookDAL.GetBookId(rentId);
            var date = DateTime.Today;

            _bookDAL.ReturnBook(new Dtos.ReturnBookDTO
            {
                RentId = rentId,
                ReturnDate = DateTime.Now
            });

            _notificationRegister.Publish("BookInEvent", JsonConvert.SerializeObject(new
            {
                BookId = bookId,
                OutDate = date
            }));

            return Json(new
            {
                result = true
            });
        }
    }
}

src/DemoModules/BookLibrary/Views/Book/AvailableBooks.cshtml
@{

}

@section Header{
    <link rel="stylesheet" href="@Url.Action("GetModuleCSS", "System", new { moduleName = BookLibrary.ModuleDefiniation.MODULE_NAME, fileName = "Content/module.css" })" />
}


<h1>Available Books</h1>

<div>
    <table class="table">
        <thead>
            <tr>
                <th>BookId</th>
                <th>Book Name</th>
                <th>ISBN</th>
                <th>Date Issued</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Count > 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.BookId</td>
                        <td>@item.BookName</td>
                        <td>@item.ISBN</td>
                        <td>@item.DateIssued.ToString("yyyy-MM-dd")</td>
                        <td><span class="btn btn-primary" onclick="rentBook('@item.BookId')">Rent</span></td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="5">No Records.</td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts{
    <script type="text/javascript">
        function rentBook(id) {
            $.ajax({
                url: '@Url.Action("RentBook","Book")?bookId=' + id,
                method: 'PUT',
                success: function (data) {
                    window.location.reload();
                }
            });
        }
    </script>

}